spring.application.name=mvc

server.port=9000


spring.datasource.url=jdbc:mysql://localhost:3306/taller_jpa
spring.datasource.username=root
spring.datasource.password=rkeyy7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create